name: Sync Backups with Main

on:
  push:
    branches:
      - main

jobs:
  sync-backup:
    runs-on: ubuntu-latest

    permissions:
      contents: write  

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'

      - name: Fetch all branches
        run: git fetch origin

      - name: Merge main into Backups
        run: |
          git checkout Backups
          git merge origin/main --no-edit || echo "No changes to merge"
          git push origin Backups
